// <auto-generated />
namespace DoAnChuyenNganh_Web_Ver4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WebsiteDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebsiteDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201810311115095_WebsiteDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
